[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.combined"
buildContext = ".."

[deploy]
healthcheckPath = "/api/backend-status"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
